INSERT INTO restaurants (id, name, address, rating) VALUES
(1,'Le Petit Souffle','Third Floor, Century City Mall, Kalayaan Avenue, Poblacion, Makati City',4.8),
(2,'Izakaya Kikufuji','Little Tokyo, 2277 Chino Roces Avenue, Legaspi Village, Makati City',4.5),
(3,'Heat - Edsa Shangri-La','Edsa Shangri-La, 1 Garden Way, Ortigas, Mandaluyong City',4.4),
(4,'Ooma','Third Floor, Mega Fashion Hall, SM Megamall, Ortigas, Mandaluyong City',4.9),
(5,'Sambo Kojin','Third Floor, Mega Atrium, SM Megamall, Ortigas, Mandaluyong City',4.8),
(6,'Din Tai Fung','Ground Floor, Mega Fashion Hall, SM Megamall, Ortigas, Mandaluyong City',4.4),
(7,'Buffet 101','Building K, SM By The Bay, Sunset Boulevard, Mall of Asia Complex (MOA), Pasay City',4),
(8,'Vikings','Building B, By The Bay, Seaside Boulevard, Mall of Asia Complex (MOA), Pasay City',4.2),
(9,'Spiral - Sofitel Philippine Plaza Manila','Plaza Level, Sofitel Philippine Plaza Manila, CCP Complex, Pasay City',4.9),
(10,'Locavore','Brixton Technology Center, 10 Brixton Street, Kapitolyo, Pasig City',4.8);

INSERT INTO menu_items (restaurant_id, item_id, name) VALUES
(1, 1, 'Grannys House Salad'), 
(1, 2, 'Mustard Potato Salad'), 
(1, 3, 'Barley Salad'),
(1, 4, 'Lentil Salad'),
(1, 5, 'Veg Caesar Salad'),
(1, 6, 'Citrus Chicken Salad'),
(2, 1, 'Caesar Salad - Bacon'),
(2, 2, 'Beetroot and Poached Pear Salad'),
(2, 3, 'Falafel'),
(2, 4, 'Coriander Kaffir Lime Chicken Skewers'),
(2, 5, 'Chicken Souvlaki'),
(2, 6, 'Chorizo and Potato'),
(2, 7, 'Mezze'),
(3, 1, 'Burrata with Caramelized Oranges'),
(3, 2, 'Turkish Lamb Koftas'),
(3, 3, 'BBQ Pork Ribs'),
(3, 4, 'Wild Mushroom Tagliatelle'),
(3, 5, 'Gluten-Free Pesto Pasta'),
(3, 6, 'Arrabiata Sauce Pasta'),
(4, 1, 'Pesto Sauce Pasta'),
(4, 2, 'Mushroom & Cream Sauce Pasta'),
(4, 3, 'Barley Risotto'),
(4, 4, 'Pesto Risotto'),
(4, 5, 'Spaghetti & Meatballs'),
(4, 6, 'Chorizo and Spinach Tagliatelle'),
(4, 7, 'Shrimp Linguine'),
(4, 8, 'Grilled Veggies'),
(5, 1, 'Baby Spinach and Ricotta Phyllo Roll'),
(5, 2, 'Sesame Crusted Tofu'),
(5, 3, 'Earth Bowl'),
(5, 4, 'Fruit and Nut Couscous'),
(5, 5, 'Sesame - crusted tofu'),
(5, 6, 'Halloumi'),
(5, 7, 'Barbeque Harissa Grilled Chicken'),
(5, 8, 'Herb Roasted Chicken'),
(6, 1, 'Lamb Kebabs With Pita'),
(6, 2, 'Lamb Stew'),
(6, 3, 'Pork Belly'),
(6, 4, 'Grilled Fish'),
(7, 1, 'Grilled Vegetable Panini'),
(7, 2, 'Mushroom & Caramelized Onion Panini'),
(7, 3, 'Smoked Chicken and Cheese Bagutte'),
(7, 4, 'Chicken Burger'),
(8, 1, 'Sly 9'),
(8, 2, 'Classic Margarita'),
(9, 1, 'Confit Pepper and Roasted Garlic Pizza'),
(9, 2, 'Burrata Pizza'),
(9, 3, 'Smoked Chicken Pizza'),
(10, 1, 'Chorizo and Sour Cream Pizza'),
(10, 2, 'Pepperoni Pizza');
